# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d830e79bb6576dee2436c859c34111f21f5952d9a8eff1128c72abef2f6a9529c0642918ccfd68339e6dd5f678c2fba96b7c78ec814c4432794ad0bcf23c788c

test:
  secret_key_base: d4909f64085173cec52b432867f25221ee6192efc3adf092ad2a479fdf94f0fabb74971af9224937adc654f6bf910e800de27298b89e7b52e6fc34908f297619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
